### ISSUE TITLE
proofs are missing from docs

### ISSUE THREAD

**Issue by tessr** [tendermint/iavl#204] opened 2020-01-31 14:31 UTC
The IAVL docs are looking great lately (thank you @AdityaSripal for the work specified in #56!) but they're missing a section on proofs. Some questions to answer include: 

- What does a merkle proof include? 
- How does a proof prove that a value is present in the tree? 
- What kinds of proofs are there (for leaf nodes, for inner nodes, root hash, etc)? 

Components that still need writeups: 

- [ ]  RangeProof
- [ ] Components of Proofs (e.g. ProofInnerNode, PathToLeaf)
- [ ] Proof of Value
- [ ] Proof of Abscence
- [ ] Proof Operator abstraction

**Comment by marbar3778** [comment] 2020-01-31 14:38
this is a duplicate of https://github.com/tendermint/iavl/issues/185. will close the other one and bring over the comment

**Comment by tessr** [comment] 2020-01-31 14:42
Ah, drat! I went looking for issues and didn't see one. I'll incorporate Aditya's checklist directly into this issue.

**Closed** 2020-05-27 10:37 UTC
